#: include kv/HomeScreen.kv
#: include kv/NeedHelp.kv
#: include kv/rohanCode.kv
#: include kv/shashwatCode.kv

GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        HomeScreen:
            name: 'HomeScreen'
            id: HomeScreen
        NeedHelp:
            name: 'NeedHelp'
            id: NeedHelp
        rohanCode:
            name: 'rohanCode'
            id: rohanCode
        shashwatCode:
            name: 'shashwatCode'
            id: shashwatCode