#: include kv/HomeScreen.kv
#: include kv/ProductPage.kv
#: include kv/HaveHelp.kv
#: include kv/ProductAddPage.kv
#: include kv/ProductEditDeletePage.kv
#: include kv/AccountLoginPage.kv
#: include kv/AccountDetailPage.kv
#: include kv/AccountSignupPage.kv
#: include kv/EditAccountPage.kv
#: include kv/OTPConfirmPage.kv

GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        HomeScreen:
            name: 'HomeScreen'
            id: HomeScreen
        ProductPage:
            name: 'ProductPage'
            id: ProductPage
        HaveHelp:
            name: 'HaveHelp'
            id: HaveHelp
        ProductAddPage:
            name: 'ProductAddPage'
            id: ProductAddPage
        ProductEditDeletePage:
            name: 'ProductEditDeletePage'
            id: ProductEditDeletePage
        AccountLoginPage:
            name: 'AccountLoginPage'
            id: AccountLoginPage
        AccountDetailPage:
            name: 'AccountDetailPage'
            id: AccountDetailPage
        AccountSignupPage:
            name: 'AccountSignupPage'
            id: AccountSignupPage
        EditAccountPage:
            name: 'EditAccountPage'
            id: EditAccountPage
        OTPConfirmPage:
            name: 'OTPConfirmPage'
            id: OTPConfirmPage