#: import utils kivy.utils

<AccountSignupPage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            rows:1
            pos_hint:{"top": 1,"right":1}
            size_hint:1,.08
            Button:
                size_hint: 1, 1
                text: "SIGNUP"
                on_release:
                    print(" SIGNUP PAGE ")

        GridLayout:
            cols: 3
            pos_hint: {"top": .9, "left": 1.4}
            size_hint: 1, .7
            Label:
                text: ""
                size_hint: .08, 1
            GridLayout:
                canvas:
                    Color:
                        rgb: utils.get_color_from_hex("FFFFFF")
                    Rectangle:
                        size: self.size
                        pos: self.pos
                rows: 9
                padding: 40
                spacing: 10
                GridLayout:
                    cols: 2
                    Label:
                        text: "NAME : "
                        color: 0,0,0,1
                    TextInput:
                        id: accountName
                        name: "accountName"
                GridLayout:
                    cols: 2
                    Label:
                        text: "E-MAIL: "
                        color: 0,0,0,1
                    TextInput:
                        id: accountEmail
                        name: "accountEmail"
                GridLayout:
                    cols: 2
                    Label:
                        text: "PHONE NUMBER : "
                        color: 0,0,0,1
                    TextInput:
                        id: accountPhoneNumber
                        name: "accountPhoneNumber"
                GridLayout:
                    cols: 2
                    Label:
                        text: "BIO : "
                        color: 0,0,0,1
                    TextInput:
                        id: accountBio
                        name: "accountBio"
                GridLayout:
                    cols: 2
                    Label:
                        text: "ADDRESS : "
                        color: 0,0,0,1
                    TextInput:
                        id: accountAddress
                        name: "accountAddress"
                GridLayout:
                    cols: 2
                    Label:
                        text: "LANDMARK : "
                        color: 0,0,0,1
                    TextInput:
                        id: accountLandmark
                        name: "accountLandmark"
                GridLayout:
                    cols: 2
                    Label:
                        text: "PASSWORD : "
                        color: 0,0,0,1
                    TextInput:
                        password: True
                        id: accountPassword
                        name: "accountPassword"
                GridLayout:
                    cols: 2
                    Label:
                        text: "CONFIRM PASSWORD : "
                        color: 0,0,0,1
                        id: accountConfirmPassword
                        name: "accountConfirmPassword"
                    TextInput:
                        password: True
                GridLayout:
                    cols: 2
                    spacing: 20
                    Button:
                        text: "LOGIN"
                        on_release:
                            app.change_screen("AccountLoginPage")
                    Button:
                        text: "SUBMIT"
                        on_release:
                            app.signupNewAccount()
            Label:
                text: ""
                size_hint: .08, 1

        GridLayout:
            canvas:
                Color:
                    rgb: 2.55,2.55,2.55
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .08, "left": 1.4}
            size_hint: 1, .08

            GridLayout:
                cols: 3
                ImageButton:
                    source: "pics/Home2.png"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                ImageButton:
                    source: "pics/Havehelp6.png"
                    on_release:
                        app.onClickAccount("HaveHelp")
                ImageButton:
                    source: "pics/myaccount3.jpeg"
                    on_release:
                        app.onClickAccount("AccountDetailPage")