#: import utils kivy.utils

<AccountLoginPage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos
        GridLayout:
            rows:1
            pos_hint:{"top": 1,"right":1}
            size_hint:1,.08
            Button:
                size_hint: 1, 1
                text: "LOGIN"
                on_release:
                    print(" LOGIN/SIGNUP PAGE ")
        GridLayout:
            cols: 3
            pos_hint: {"top": .86, "left": 1.4}
            size_hint: 1, .4
            Label:
                text: ""
                size_hint: .08, 1
            GridLayout:
                canvas:
                    Color:
                        rgb: utils.get_color_from_hex("FFFFFF")
                    Rectangle:
                        size: self.size
                        pos: self.pos
                rows: 3
                padding: 40
                spacing: 35
                GridLayout:
                    cols: 2
                    Label:
                        text: "E-MAIL : "
                        color: 0,0,0,1
                    TextInput:
                        id: AccountLoginEmail
                        name: "AccountLoginEmail"
                GridLayout:
                    cols: 2
                    Label:
                        text: "PASSWORD : "
                        color: 0,0,0,1
                    TextInput:
                        password: True
                        id: AccountLoginPassword
                        name: "AccountLoginPassword"
                GridLayout:
                    cols: 2
                    spacing: 5
                    Button:
                        text: "SIGNUP"
                        on_release:
                            app.change_screen("AccountSignupPage")
                    Button:
                        text: "SUBMIT"
                        on_release:
                            app.LoginEmailPasswordCheck()
            Label:
                text: ""
                size_hint: .08, 1

        GridLayout:
            canvas:
                Color:
                    rgb: 2.55,2.55,2.55
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .08, "left": 1.4}
            size_hint: 1, .08

            GridLayout:
                cols: 3
                ImageButton:
                    source: "pics/Home2.png"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                ImageButton:
                    source: "pics/Havehelp6.png"
                    on_release:
                        app.onClickAccount("HaveHelp")
                ImageButton:
                    source: "pics/myaccount3.jpeg"
                    on_release:
                        app.onClickAccount("AccountDetailPage")