#: import utils kivy.utils

<AccountSignupPage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            cols: 3
            pos_hint: {"top": .9, "left": 1.4}
            size_hint: 1, .7
            Label:
                text: ""
                size_hint: .08, 1
            GridLayout:
                canvas:
                    Color:
                        rgb: utils.get_color_from_hex("2097F3")
                    Rectangle:
                        size: self.size
                        pos: self.pos
                rows: 9
                padding: 40
                spacing: 10
                GridLayout:
                    cols: 2
                    Label:
                        text: "Name: "
                    TextInput:
                        id: accountName
                        name: "accountName"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Email: "
                    TextInput:
                        id: accountEmail
                        name: "accountEmail"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Phone Number: "
                    TextInput:
                        id: accountPhoneNumber
                        name: "accountPhoneNumber"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Bio: "
                    TextInput:
                        id: accountBio
                        name: "accountBio"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Address: "
                    TextInput:
                        id: accountAddress
                        name: "accountAddress"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Landmark: "
                    TextInput:
                        id: accountLandmark
                        name: "accountLandmark"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Password: "
                    TextInput:
                        password: True
                        id: accountPassword
                        name: "accountPassword"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Confirm Password: "
                        id: accountConfirmPassword
                        name: "accountConfirmPassword"
                    TextInput:
                        password: True
                GridLayout:
                    cols: 2
                    spacing: 20
                    Button:
                        text: "Login"
                        on_release:
                            app.change_screen("AccountLoginPage")
                    Button:
                        text: "submit"
                        on_release:
                            app.signupNewAccount()
            Label:
                text: ""
                size_hint: .08, 1

        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("2097F3")
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .10, "left": 1.4}
            size_hint: 1, .1

            GridLayout:
                cols: 3
                Button:
                    text: "Home"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                Button:
                    text: "Have Help"
                    on_release:
                        app.onClickAccount("HaveHelp")
                Button:
                    text: "Account"
                    on_release:
                        app.onClickAccount("AccountDetailPage")