#: import utils kivy.utils

<HaveHelp>:
    FloatLayout:

        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos




        GridLayout:
            cols: 3
            pos_hint: {"top": 0.85, "left": 1}
            size_hint: 1, 0.55
            Label:
                size_hint: 0.1, 0.35
                text: ""
            DropDown:
                auto_dismiss: False
                pos_hint: {"top": 0.7, "left": 1}
                size_hint: 1, 0.3
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product1
                        name: "Product1"
                        on_release:
                            app.updateProductPageUI(1)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product2
                        name: "Product2"
                        on_release:
                            app.updateProductPageUI(2)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product3
                        name: "Product3"
                        on_release:
                            app.updateProductPageUI(3)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product4
                        name: "Product4"
                        on_release:
                            app.updateProductPageUI(4)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product5
                        name: "Product5"
                        on_release:
                            app.updateProductPageUI(5)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product6
                        name: "Product6"
                        on_release:
                            app.updateProductPageUI(6)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product7
                        name: "Product7"
                        on_release:
                            app.updateProductPageUI(7)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product8
                        name: "Product8"
                        on_release:
                            app.updateProductPageUI(8)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product9
                        name: "Product9"
                        on_release:
                            app.updateProductPageUI(9)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: 60
                    Button:
                        text: ""
                        id: Product10
                        name: "Product10"
                        on_release:
                            app.updateProductPageUI(10)
                    Button:
                        size_hint: .2, 1
                        text: "Edit"
                        on_release:
                            app.change_screen("ProductEditDeletePage")
            Label:
                size_hint: 0.1, 0.35
                text: ""


        GridLayout:
            cols: 3
            pos_hint: {"top": 0.28, "left": 1}
            size_hint: 1, 0.1
            Label:
                size_hint: 0.7, 0.35
                text: ""
            Button:
                text: "+"
                on_release:
                    app.change_screen("ProductAddPage")
            Label:
                size_hint: 0.7, 0.35
                text: ""

        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("2097F3")
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .10, "left": 1.4}
            size_hint: 1, .1

            GridLayout:
                cols: 3
                Button:
                    text: "Home"
                    on_release:
                        app.change_screen("HomeScreen")
                Button:
                    text: "Have Help"
                    on_release:
                        app.onClickAccount("HaveHelp")
                Button:
                    text: "Account"
                    on_release:
                        app.onClickAccount("AccountDetailPage")