#: import utils kivy.utils

<HomeScreen>:
    FloatLayout:

        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            cols: 2
            pos_hint: {"top": .96, "left": 1.4}
            size_hint: .8, .06

            Label:
                color: 0, 0, 0, 1
                size_hint: 0.5, 1
                font_size: '18sp'
                size_hint: 1, .6
                text: "Help Required"

            DropDown:
                auto_dismiss: False
                pos_hint: {"top": 1, "left": 1}
                size_hint: 1, 1
                Button:
                    text: "Bed"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "Medecin"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "Oxygen"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "Bear"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "Rum"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "Vodka"
                    size_hint_y: None
                    height: 30

        GridLayout:
            cols: 2
            pos_hint: {"top": .88, "left": 1}
            size_hint: .8, .06

            Label:
                color: 0, 0, 0, 1
                size_hint: 0.5, 1
                font_size: '18sp'
                size_hint: 1, .4
                text: "Range"

            DropDown:
                auto_dismiss: False
                pos_hint: {"top": 1, "left": 1}
                size_hint: 1, .6
                Button:
                    text: "5 km"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "10 km"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "15 km"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "20 km"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "25 km"
                    size_hint_y: None
                    height: 30
                Button:
                    text: "30 km"
                    size_hint_y: None
                    height: 30


        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("2097F3")
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .10, "left": 1.4}
            size_hint: 1, .1

            GridLayout:
                cols: 3
                Button:
                    text: "Home"
                    on_release:
                        app.change_screen("HomeScreen")
                Button:
                    text: "Have Help"
                    on_release:
                        app.change_screen("HaveHelp")
                Button:
                    text: "Account"
                    on_release:
                        app.change_screen("AccountLoginPage")

        GridLayout:
            cols: 3
            pos_hint: {"top": 0.7, "left": 1}
            size_hint: 1, 0.55
            Label:
                size_hint: 0.1, 0.35
                text: ""
            DropDown:
                auto_dismiss: False
                pos_hint: {"top": 0.7, "left": 1}
                size_hint: 1, 0.3
                Button:
                    text: "NAME:        Rohan Gupta\nPRODUCT:      Bed\nDISTANCE:    12Km"
                    size_hint_y: None
                    height: 60
                    on_release:
                        app.change_screen("ProductPage")
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: ACCOUNTDETAILS "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
                Button:
                    text: "NAME: \nPRODUCT: \nDISTANCE: "
                    size_hint_y: None
                    height: 60
            Label:
                size_hint: 0.1, 0.35
                text: ""