#: import utils kivy.utils

<HomeScreen>:
    FloatLayout:

        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            rows: 2
            Button:
                text: "Rohan Code"
                on_release:
                    app.change_screen("rohanCode")

            Button:
                text: "Shashwat Code"
                on_release:
                    app.change_screen("shashwatCode")

        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("2097F3")
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .10, "left": 1.4}
            size_hint: 1, .1

            GridLayout:
                rows: 3
                size_hint: 0.3, 1
                Label:
                    size_hint: 0.1, 0.35
                    text: ""
                Image:
                    source: "pics/home.png"
                Label:
                    text: "Home"
            GridLayout:
                rows: 3
                size_hint: 0.3, 1
                Label:
                    size_hint: 0.1, 0.35
                    text: ""
                Image:
                    source: "pics/hand.png"
                Label:
                    text: "Need Help"
            GridLayout:
                rows: 3
                size_hint: 0.3, 1
                Label:
                    size_hint: 0.1, 0.35
                    text: ""
                Image:
                    source: "pics/help.png"
                Label:
                    text: "Can Help"


