#: import utils kivy.utils

<ProductEditDeletePage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            rows:1
            pos_hint:{"top": 1,"right":1}
            size_hint:1,.08
            Button:
                size_hint: 1, 1
                text: "PRODUCT EDIT/DELETE"
                on_release:
                    print("")

        GridLayout:
            cols: 3
            pos_hint: {"top": .9, "left": 1.4}
            size_hint: 1, .7
            Label:
                text: ""
                size_hint: .08, 1
            GridLayout:
                canvas:
                    Color:
                        rgb: utils.get_color_from_hex("2097F3")
                    Rectangle:
                        size: self.size
                        pos: self.pos
                rows: 7
                padding: 40
                spacing: 20
                GridLayout:
                    cols: 2
                    Label:
                        text: "Name: "
                    TextInput:
                        id: name
                        name: "name"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Description: "
                    TextInput:
                        id: description
                        name: "description"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Quantity: "
                    TextInput:
                        id: quantity
                        name: "quantity"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Address: "
                    TextInput:
                        id: address
                        name: "address"
                GridLayout:
                    cols: 2
                    Label:
                        text: "Landmark: "
                    TextInput:
                        id: landmark
                        name: "landmark"
                GridLayout:
                    cols: 2
                    spacing: 20
                    Button:
                        text: "Delete"
                        on_release:
                            app.DeleteProductFromDatabase()
                    Button:
                        text: "submit"
                        on_release:
                            app.UpdateProductDetailInDatabase()
            Label:
                text: ""
                size_hint: .08, 1

        GridLayout:
            canvas:
                Color:
                    rgb: 2.55,2.55,2.55
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .08, "left": 1.4}
            size_hint: 1, .08

            GridLayout:
                cols: 3
                ImageButton:
                    source: "pics/Home2.png"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                ImageButton:
                    source: "pics/Havehelp6.png"
                    on_release:
                        app.onClickAccount("HaveHelp")
                ImageButton:
                    source: "pics/myaccount3.jpeg"
                    on_release:
                        app.onClickAccount("AccountDetailPage")