#: import utils kivy.utils

<ProductAddPage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos
        GridLayout:
            rows:1
            pos_hint:{"top": 1,"right":1}
            size_hint:1,.08
            Button:
                size_hint: 1, 1
                text: "ADD PRODUCT"
                on_release:
                    print("")
        GridLayout:
            cols: 3
            pos_hint: {"top": .9, "left": 1.4}
            size_hint: 1, .7
            Label:
                text: ""
                size_hint: .08, 1
            GridLayout:
                canvas:
                    Color:
                        rgb: utils.get_color_from_hex("FFFFFF")
                    Rectangle:
                        size: self.size
                        pos: self.pos
                rows: 8
                padding: 40
                spacing: 20
                GridLayout:
                    cols: 2
                    Label:
                        text: "NAME:  "
                        color:0,0,0,1
                    TextInput:
                        id: productName
                        name: "productName"
                GridLayout:
                    cols: 2
                    Label:
                        text: "DESCRIPTION : "
                        color: 0,0,0,1
                    TextInput:
                        id: productDescription
                        name: "productDescription"
                GridLayout:
                    cols: 2
                    Label:
                        text: "PRODUCT TYPE : "
                        color: 0,0,0,1
                    DropDown:
                        auto_dismiss: False
                        size_hint: 1, .8
                        Button:
                            text: "Bed"
                            size_hint_y: None
                            height: 26
                            on_release:
                                app.setProductType("Bed")
                        Button:
                            text: "Oxygen"
                            size_hint_y: None
                            height: 26
                            on_release:
                                app.setProductType("Oxygen")
                        Button:
                            text: "Medicen"
                            size_hint_y: None
                            height: 26
                            on_release:
                                app.setProductType("Medicen")
                GridLayout:
                    cols: 2
                    Label:
                        text: "QUANTITY : "
                        color: 0,0,0,1
                    TextInput:
                        id: productQuantity
                        name: "productQuantity"
                GridLayout:
                    cols: 2
                    Label:
                        text: "ADDRESS : "
                        color: 0,0,0,1
                    DropDown:
                        auto_dismiss: False
                        size_hint: 1, .8
                        Button:
                            text: "Orignal Address"
                            size_hint_y: None
                            height: 26
                        TextInput:
                            size_hint_y: None
                            height: 26
                            id: productAddress
                            name: "productAddress"
                GridLayout:
                    cols: 2
                    Label:
                        text: "LANDMARK : "
                        color:0,0,0,1
                    TextInput:
                        id: productLandmark
                        name: "productLandmark"
                GridLayout:
                    cols: 1
                    spacing: 20
                    Button:
                        text: "SUBMIT"
                        on_release:
                            app.addNewProduct()
            Label:
                text: ""
                size_hint: .08, 1

        GridLayout:
            canvas:
                Color:
                    rgb: 2.55,2.55,2.55
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .08, "left": 1.4}
            size_hint: 1, .08

            GridLayout:
                cols: 3
                ImageButton:
                    source: "pics/Home2.png"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                ImageButton:
                    source: "pics/Havehelp6.png"
                    on_release:
                        app.onClickAccount("HaveHelp")
                ImageButton:
                    source: "pics/myaccount3.jpeg"
                    on_release:
                        app.onClickAccount("AccountDetailPage")