#: import utils kivy.utils

<ProductEditDeletePage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("FFFFFF")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            rows:1
            pos_hint:{"top": 1,"right":1}
            size_hint:1,.08
            Button:
                size_hint: 1, 1
                text: "PRODUCT EDIT/DELETE"
                on_release:
                    print("")

        GridLayout:
            cols: 3
            pos_hint: {"top": .9, "left": 1.4}
            size_hint: 1, .7
            Label:
                text: ""
                size_hint: .08, 1
            GridLayout:
                canvas:
                    Color:
                        rgb: utils.get_color_from_hex("2097F3")
                    Rectangle:
                        size: self.size
                        pos: self.pos
                rows: 8
                padding: 40
                spacing: 20
                GridLayout:
                    cols: 2
                    Label:
                        text: "Name: "
                    TextInput:
                GridLayout:
                    cols: 2
                    Label:
                        text: "Description: "
                    TextInput:
                GridLayout:
                    cols: 2
                    Label:
                        text: "Product Type: "
                    DropDown:
                        auto_dismiss: False
                        size_hint: 1, .8
                        Button:
                            text: "Bed"
                            size_hint_y: None
                            height: 26
                        Button:
                            text: "Oxygen"
                            size_hint_y: None
                            height: 26
                        Button:
                            text: "Medicen"
                            size_hint_y: None
                            height: 26
                GridLayout:
                    cols: 2
                    Label:
                        text: "Quantity: "
                    TextInput:
                GridLayout:
                    cols: 2
                    Label:
                        text: "Address: "
                    DropDown:
                        auto_dismiss: False
                        size_hint: 1, .8
                        Button:
                            text: "Orignal Address"
                            size_hint_y: None
                            height: 26
                        TextInput:
                            size_hint_y: None
                            height: 26
                GridLayout:
                    cols: 2
                    Label:
                        text: "Landmark: "
                    TextInput:
                GridLayout:
                    cols: 1
                    spacing: 20
                    Button:
                        text: "submit"
                        on_release:
                            app.change_screen("HaveHelp")
            Label:
                text: ""
                size_hint: .08, 1

        GridLayout:
            canvas:
                Color:
                    rgb: 2.55,2.55,2.55
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .08, "left": 1.4}
            size_hint: 1, .08

            GridLayout:
                cols: 3
                ImageButton:
                    source: "pics/Home2.png"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                ImageButton:
                    source: "pics/Havehelp6.png"
                    on_release:
                        app.onClickAccount("HaveHelp")
                ImageButton:
                    source: "pics/myaccount3.jpeg"
                    on_release:
                        app.onClickAccount("AccountDetailPage")