#: import utils kivy.utils

<ProductPage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("CAAFAA")
            Rectangle:
                size: self.size
                pos: self.pos
        GridLayout:
            rows:2
            pos_hint:{"top": 1.1,"right":1}
            size_hint:1,.5
            ImageButton:
                source: "pics/Oxygen Cylinder.jpeg"
                on_release:
                    print("OPENS PRODUCT's IMAGE")
        GridLayout:

            cols: 2
            pos_hint: {"top": .34, "right": .8}
            size_hint: .6, .06

            Label:
                color: 0, 0, 0, 1
                size_hint: 0.5, 1
                font_size: '18sp'
                size_hint: 1, .6
                text: "NAME OF SELLER : Melon Husk\nPRODUCT NAME : Oxygen\nPRODUCT TYPE : Utility\nQUANTITY : 1k\nPRODUCT DESCRIPTION : Breathe this and\nSave your fucking lives\nPRODUCT ADDRESS :Wherever the hell you\nwant it to be \nLANNDMARK :Told You Already \nSELLER PHONE NO. :123456789\nE-MAIL : Mail it on\ntesla@husk.com"
        GridLayout:
            canvas:
                Color:
                    rgb:utils.get_color_from_hex("67697C")
                Rectangle:
                    size: self.size
                    pos:self.pos
            rows:1
            pos_hint:{"top": .7,"right":1}
            size_hint:1,.17
            ImageButton:
                source:"pics/EM.jpeg"
                on_release:
                    print("OPEN SELLER's IMAGE")
        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("2097F3")
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .10, "left": 1.4}
            size_hint: 1, .1

            GridLayout:
                cols: 3
                Button:
                    text: "Home"
                    on_release:
                        app.change_screen("HomeScreen")
                Button:
                    text: "Have Help"
                    on_release:
                        app.onClickAccount("HaveHelp")
                Button:
                    text: "Account"
                    on_release:
                        app.onClickAccount("AccountDetailPage")