#: import utils kivy.utils

<ProductPage>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("CAAFAA")
            Rectangle:
                size: self.size
                pos: self.pos

        GridLayout:
            rows:2
            pos_hint:{"top": 1.1,"right":1}
            size_hint: 1, 0.5
            ImageButton:
                source: "pics/Oxygen Cylinder.jpeg"
                on_release:
                    print("OPENS PRODUCT's IMAGE")

        GridLayout:
            rows: 9
            pos_hint: {"top": .5, "right": .8}
            size_hint: .6, .3

            Label:
                color: 0, 0, 0, 1
                text: "NAME OF SELLER : "
                id: sellerName
                name: "sellerName"
            Label:
                color: 0, 0, 0, 1
                text: "PRODUCT NAME : "
                id: productName
                name: "productName"
            Label:
                color: 0, 0, 0, 1
                text: "PRODUCT TYPE : "
                id: productType
                name: "productType"
            Label:
                color: 0, 0, 0, 1
                text: "QUANTITY : "
                id: quantity
                name: "quantity"
            Label:
                color: 0, 0, 0, 1
                text: "PRODUCT DESCRIPTION : "
                id: productDescription
                name: "productDescription"
            Label:
                color: 0, 0, 0, 1
                text: "PRODUCT ADDRESS : "
                id: productAddress
                name: "productAddress"
            Label:
                color: 0, 0, 0, 1
                text: "LANDMARK : "
                id: landmark
                name: "landmark"
            Label:
                color: 0, 0, 0, 1
                text: "SELLER PHONE NO : "
                id: sellerNumber
                name: "sellerNumber"
            Label:
                color: 0, 0, 0, 1
                text: "E-MAIL : "
                id: sellerEmail
                name: "sellerEmail"
        GridLayout:
            canvas:
                Color:
                    rgb:utils.get_color_from_hex("CAAFAA")
                Rectangle:
                    size: self.size
                    pos:self.pos
            rows:1
            pos_hint:{"top": .7,"right":1}
            size_hint:1,.17
            ImageButton:
                source:"pics/EM7.png"
                on_release:
                    print("OPEN SELLER's IMAGE")
        GridLayout:
            canvas:
                Color:
                    rgb: 2.55,2.55,2.55
                Rectangle:
                    size: self.size
                    pos: self.pos
            cols: 3
            pos_hint: {"top": .08, "left": 1.4}
            size_hint: 1, .08

            GridLayout:
                cols: 3
                ImageButton:
                    source: "pics/Home2.png"
                    on_release:
                        app.DefaultProductListOnHomeScreen()
                ImageButton:
                    source: "pics/Havehelp6.png"
                    on_release:
                        app.onClickAccount("HaveHelp")
                ImageButton:
                    source: "pics/myaccount3.jpeg"
                    on_release:
                        app.onClickAccount("AccountDetailPage")