#: import utils kivy.utils
<shashwatCode>:
    FloatLayout:
        GridLayout:
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("FAAAFF")
                Rectangle:
                    size: self.size
                    pos: self.pos
        FloatLayout:
            GridLayout:
                cols:3
                Label:
                    pos_hint: {"top":.9,"right":.4}
                    size_hint: .1, .1
                    text:'Gap :'
                Button:
                    pos_hint:{"top":.5,"right":.1}
                    size_hint: .4,.4
                    text:"NAME : \nPRODUCT : \nDISTANCE : "
                Label:
                    pos_hint: {"top":.8,"left":.1}
                    size_hint: .7, .1
                    text:'  Gap :'
